fix get/set brightness for sonypi/spiccrtl
This patch fixes the get/set LCD brightness code for machines which supported
by the sonypi kernel module and set/get py spicctrl. Added also some checks
and a new error message if spicctrl is not available/executable and allow
also spiccrtl in /usr/bin.

diff --git a/tools/linux/hal-system-lcd-get-brightness-linux b/tools/linux/hal-system-lcd-get-brightness-linux
--- a/tools/linux/hal-system-lcd-get-brightness-linux
+++ b/tools/linux/hal-system-lcd-get-brightness-linux
@@ -61,7 +61,17 @@ elif [ "$HAL_PROP_LAPTOP_PANEL_ACCESS_METHOD" = "sonypi" ]; then
 	# spicctrl -B
 	# 70
 	# 0..255
-	value="`/usr/sbin/spicctrl -B`"
+	if [ -x /usr/sbin/spicctrl ]; then
+		SPICCRTL="/usr/sbin/spicctrl"
+        elif [ -x /usr/bin/spicctrl ]; then
+		SPICCRTL="/usr/bin/spicctrl"
+	else
+                echo "org.freedesktop.Hal.Device.LaptopPanel.NotSupported" >&2
+                echo "spicctrl not found or not executable" >&2
+                exit 1;
+        fi
+
+	value="`$SPICCRTL -B`"
 	RETVAL=$?
 	if [ $RETVAL != 0 ]; then
 		echo "org.freedesktop.Hal.Device.LaptopPanel.NotSupported" >&2
