Use new property on the hal device object to figure out where hal mounted     the device. This also ensures we only unmount stuff that we mounted     ourselves ... where we = the hal mount/unmount methods. Also only allow     the user who mounted the volume to unmount it (also allow uid 0). Allow mounting of drives we don't poll. Export mount point and what uid     mounted it as properties on the hal device object Fix up detection of blank and audio discs for the purpose of adding Eject     methods. Export Mount, Unmount and Eject methods on drives we don't     poll. Give some leeway with what mount options we support.

diff --git a/tools/hal-system-storage-unmount b/tools/hal-system-storage-unmount
--- a/tools/hal-system-storage-unmount
+++ b/tools/hal-system-storage-unmount
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 # Copyright (C) 2005, Kay Sievers <kay.sievers@vrfy.org>
+# Copyright (C) 2006, David Zeuthen <david@fubar.dk>
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License version 2.
@@ -12,10 +13,27 @@ if [ "$HAL_PROP_BLOCK_DEVICE" == "" ] || [ "$HAL_PROP_INFO_UDI" == "" ] ; then
     exit 1
 fi
 
-if [ "$HAL_PROP_VOLUME_IS_MOUNTED" != "true" ]; then
+MOUNT_POINT="$HAL_PROP_INFO_HAL_MOUNT_CREATED_MOUNT_POINT"
+if [ "$MOUNT_POINT" == "" ]; then
     echo "org.freedesktop.Hal.Device.Volume.NotMounted" >&2
-    echo "Device is not mounted." >&2
+    echo "Cannot figure out where device is mounted." >&2
     exit 1
+fi
+
+if [ "$HAL_PROP_STORAGE_MEDIA_CHECK_ENABLED" != "false" ]; then
+    if [ "$HAL_PROP_VOLUME_IS_MOUNTED" != "true" ]; then
+	echo "org.freedesktop.Hal.Device.Volume.NotMounted" >&2
+	echo "Device is not mounted." >&2
+	exit 1
+    fi
+fi
+
+if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ]; then
+    if [ "$HAL_METHOD_INVOKED_BY_UID" != "$HAL_PROP_INFO_HAL_MOUNT_MOUNTED_BY_UID" ]; then
+	echo "org.freedesktop.Hal.Device.Volume.PermissionDenied" >&2
+	echo "Volume mounted by uid $HAL_PROP_INFO_HAL_MOUNT_MOUNTED_BY_UID cannot be unmounted by uid $HAL_METHOD_INVOKED_BY_UID." >&2
+	exit 1
+    fi
 fi
 
 # read parameters
@@ -59,7 +77,7 @@ if [ "$GIVEN_UNMOUNTOPTIONS" != "" ]; then
     done
 fi
 
-RESULT=$(umount $UNMOUNTOPTIONS "$HAL_PROP_VOLUME_MOUNT_POINT" 2>&1)
+RESULT=$(umount $UNMOUNTOPTIONS "$MOUNT_POINT"  2>&1)
 if [ $? -ne 0 ]; then
     case "$RESULT" in
 	*busy*)
@@ -78,9 +96,12 @@ if [ $? -ne 0 ]; then
 fi
 
 # remove directory only if HAL has created it
-if [ -e $HAL_PROP_VOLUME_MOUNT_POINT/.created-by-hal ]; then
-  rm -f $HAL_PROP_VOLUME_MOUNT_POINT/.created-by-hal
-  rmdir --ignore-fail-on-non-empty "$HAL_PROP_VOLUME_MOUNT_POINT"
+if [ -e $MOUNT_POINT/.created-by-hal ]; then
+  rm -f $MOUNT_POINT/.created-by-hal
+  rmdir --ignore-fail-on-non-empty "$MOUNT_POINT"
 fi
+
+hal-set-property --udi $UDI --key info.hal_mount.created_mount_point --remove > /dev/null 2>&1
+hal-set-property --udi $UDI --key info.hal_mount.mounted_by_uid --remove > /dev/null 2>&1
 
 exit 0
