use libsmbios to add support for bluetooth, wlan RF kill on Dell laptops

diff --git a/tools/hal-system-killswitch-set-power b/tools/hal-system-killswitch-set-power
--- a/tools/hal-system-killswitch-set-power
+++ b/tools/hal-system-killswitch-set-power
@@ -8,17 +8,21 @@
 # (at your option) any later version.
 
 # Check for environment variables
-if [ -z "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" ]; then
+if [ -z "$HAL_PROP_KILLSWITCH_ACCESS_METHOD" ] ; then
         echo "org.freedesktop.Hal.Device.UnknownError" >&2
-	echo "Missing or empty environment variable(s)." >&2
-	echo "This script should be started by hald." >&2
-	exit 1
+        echo "Missing or empty environment variable(s)." >&2
+        echo "This script should be started by hald." >&2
+        exit 1
 fi
 
 # TODO: check privilege
 
-if [ -n "$HALD_UNAME_S" -a -x ./$HALD_UNAME_S/hal-system-bluetooth-get-power-$HALD_UNAME_S ]; then
-    exec ./$HALD_UNAME_S/hal-system-bluetooth-get-power-$HALD_UNAME_S $@
+# read value for set bluetooth power
+read value
+export value
+
+if [ -n "$HALD_UNAME_S" -a -x ./$HALD_UNAME_S/hal-system-killswitch-set-power-$HALD_UNAME_S ]; then
+    exec ./$HALD_UNAME_S/hal-system-killswitch-set-power-$HALD_UNAME_S $@
 else
     echo "org.freedesktop.Hal.Device.UnknownError" >&2
     echo "No back-end for your operating system" >&2
