Attempt to use volume.mount_point if we cannot find     info.hal_mount.created_mount_point Export prototype for new function libhal_ctx_get_dbus_connection() New function Use a the Unmount() hal method to lazy unmount Ugh ugh ugh.. clear buffer before receiving data from udev.. we didn't use     to do this and we got all sorts of weird side-effects since we'd for     instance pick up DEVNAME='/dev/sdb' and _then_ DEVNAME='/dev/sda1' for     /sys/block/sdb.. This was because this data was left in the buffer from     the old run. It now appears to work.. New function, pass end_token to hal_util_callout_device_remove()     (force_unmount): Use the Unmount method call to lazy unmount, thus     making sure we don't block (hotplug_event_begin_remove_blockdev): Pass     end_token to force_unmount and let that function invoke     hal_util_callout_device_remove() Make this work for helpers using a direct connection to hald     (hald_dbus_filter_handle_methods): Pass local_interface to     hald_exec_method Update to use 'pwd' just like run-hald.sh was updated

diff --git a/tools/hal-system-storage-unmount b/tools/hal-system-storage-unmount
--- a/tools/hal-system-storage-unmount
+++ b/tools/hal-system-storage-unmount
@@ -15,9 +15,12 @@ fi
 
 MOUNT_POINT="$HAL_PROP_INFO_HAL_MOUNT_CREATED_MOUNT_POINT"
 if [ "$MOUNT_POINT" == "" ]; then
-    echo "org.freedesktop.Hal.Device.Volume.NotMounted" >&2
-    echo "Cannot figure out where device is mounted." >&2
-    exit 1
+    MOUNT_POINT="$HAL_PROP_VOLUME_MOUNT_POINT"
+    if [ "$MOUNT_POINT" == "" ]; then
+	echo "org.freedesktop.Hal.Device.Volume.NotMounted" >&2
+	echo "Cannot figure out where device is mounted." >&2
+	exit 1
+    fi
 fi
 
 if [ "$HAL_PROP_STORAGE_MEDIA_CHECK_ENABLED" != "false" ]; then
@@ -30,8 +33,12 @@ fi
 
 if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ]; then
     if [ "$HAL_METHOD_INVOKED_BY_UID" != "$HAL_PROP_INFO_HAL_MOUNT_MOUNTED_BY_UID" ]; then
+	UID_MOUNTED="$HAL_PROP_INFO_HAL_MOUNT_MOUNTED_BY_UID"
+	if [ "$UID_MOUNTED" == "" ]; then
+	    UID_MOUNTED="UNKNOWN"
+	fi
 	echo "org.freedesktop.Hal.Device.Volume.PermissionDenied" >&2
-	echo "Volume mounted by uid $HAL_PROP_INFO_HAL_MOUNT_MOUNTED_BY_UID cannot be unmounted by uid $HAL_METHOD_INVOKED_BY_UID." >&2
+	echo "Volume mounted by uid $UID_MOUNTED cannot be unmounted by uid $HAL_METHOD_INVOKED_BY_UID." >&2
 	exit 1
     fi
 fi
