Fixed path to the helper of the related backends, added several messages as     e.g. UnknownError if backend not found (William Jon McCann     <mccann@jhu.edu>) and if a needed environment variable is not set.     Capture result of command polkit-is-privileged (William i Jon McCann     <mccann@jhu.edu>) added PACKAGE_BIN_DIR to PATH export MOUNT_POINT for the backend script William Jon McCann     <mccann@jhu.edu> added result of failed eject to error message (<mccann@jhu.edu>), added     GIVEN_EJECTOPTIONS to the eject command

diff --git a/tools/hal-luks-teardown b/tools/hal-luks-teardown
--- a/tools/hal-luks-teardown
+++ b/tools/hal-luks-teardown
@@ -8,14 +8,16 @@
 
 # Check for environment variables
 if [ -z "$HAL_PROP_BLOCK_DEVICE" ] || [ -z "$HAL_PROP_INFO_UDI" ] || [ -z "$HAL_PROP_VOLUME_UUID" ] ; then
+        echo "org.freedesktop.Hal.Device.UnknownError" >&2
         echo "Missing or empty environment variable(s)." >&2
         echo "This script should be started by hald." >&2
         exit 1
 fi
 
-if [ -n "$HALD_UNAME_S" -a -x ./$0-$HALD_UNAME_S ]; then
-    exec ./$0-$HALD_UNAME_S $@
+if [ -n "$HALD_UNAME_S" -a -x $0-$HALD_UNAME_S ]; then
+    exec $0-$HALD_UNAME_S $@
 else
+    echo "org.freedesktop.Hal.Device.UnknownError" >&2
     echo "No back-end for your operating system" >&2
     exit 1
 fi
diff --git a/tools/hal-system-lcd-set-brightness b/tools/hal-system-lcd-set-brightness
--- a/tools/hal-system-lcd-set-brightness
+++ b/tools/hal-system-lcd-set-brightness
@@ -10,6 +10,7 @@
 # Check for environment variables
 if [ -z "$HAL_PROP_LAPTOP_PANEL_ACCESS_METHOD" ] || 
    [ -z "$HAL_PROP_LAPTOP_PANEL_NUM_LEVELS" ] ; then
+        echo "org.freedesktop.Hal.Device.UnknownError" >&2
         echo "Missing or empty environment variable(s)." >&2
         echo "This script should be started by hald." >&2
         exit 1
@@ -27,9 +28,10 @@ fi
 
 export value
 
-if [ -n "$HALD_UNAME_S" -a -x ./$0-$HALD_UNAME_S ]; then
-    exec ./$0-$HALD_UNAME_S $@
+if [ -n "$HALD_UNAME_S" -a -x $0-$HALD_UNAME_S ]; then
+    exec $0-$HALD_UNAME_S $@
 else
+    echo "org.freedesktop.Hal.Device.UnknownError" >&2
     echo "No back-end for your operating system" >&2
     exit 1
 fi
diff --git a/tools/hal-system-power-shutdown b/tools/hal-system-power-shutdown
--- a/tools/hal-system-power-shutdown
+++ b/tools/hal-system-power-shutdown
@@ -2,7 +2,7 @@
 
 POLICY=hal-power-poweroff
 if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ] ; then
-    polkit-is-privileged --privilege $POLICY --user $HAL_METHOD_INVOKED_BY_UID
+    RESULT=$(polkit-is-privileged --privilege $POLICY --user $HAL_METHOD_INVOKED_BY_UID 2>&1)
     IS_PRIVILEGED=$?
     if [ "$IS_PRIVILEGED" != "0" ] ; then
 	echo org.freedesktop.Hal.Device.PermissionDeniedByPolicy >&2
@@ -11,9 +11,10 @@ if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ] ; then
     fi
 fi
 
-if [ -n "$HALD_UNAME_S" -a -x ./$0-$HALD_UNAME_S ]; then
-    exec ./$0-$HALD_UNAME_S $@
+if [ -n "$HALD_UNAME_S" -a -x $0-$HALD_UNAME_S ]; then
+    exec $0-$HALD_UNAME_S $@
 else
+    echo "org.freedesktop.Hal.Device.UnknownError" >&2
     echo "No back-end for your operating system" >&2
     exit 1
 fi
diff --git a/tools/hal-system-storage-cleanup-mountpoint b/tools/hal-system-storage-cleanup-mountpoint
--- a/tools/hal-system-storage-cleanup-mountpoint
+++ b/tools/hal-system-storage-cleanup-mountpoint
@@ -6,6 +6,7 @@
 # it under the terms of the GNU General Public License version 2.
 
 if [ -z "$HALD_CLEANUP" ]; then
+    echo "org.freedesktop.Hal.Device.UnknownError" >&2
     echo Specify directory to clean up with the environment variable HALD_CLEANUP
     exit 1
 fi
diff --git a/tools/hal-system-storage-cleanup-mountpoints b/tools/hal-system-storage-cleanup-mountpoints
--- a/tools/hal-system-storage-cleanup-mountpoints
+++ b/tools/hal-system-storage-cleanup-mountpoints
@@ -6,9 +6,10 @@
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License version 2.
 
-if [ -n "$HALD_UNAME_S" -a -x ./$0-$HALD_UNAME_S ]; then
-    exec ./$0-$HALD_UNAME_S $@
+if [ -n "$HALD_UNAME_S" -a -x $0-$HALD_UNAME_S ]; then
+    exec $0-$HALD_UNAME_S $@
 else
+    echo "org.freedesktop.Hal.Device.UnknownError" >&2
     echo "No back-end for your operating system" >&2
     exit 1
 fi
diff --git a/tools/hal-system-storage-unmount b/tools/hal-system-storage-unmount
--- a/tools/hal-system-storage-unmount
+++ b/tools/hal-system-storage-unmount
@@ -8,6 +8,7 @@
 
 # Check for environment variables
 if [ -z "$HAL_PROP_BLOCK_DEVICE" ] || [ -z "$HAL_PROP_INFO_UDI" ] ; then
+    echo "org.freedesktop.Hal.Device.UnknownError" >&2
     echo "Missing or empty environment variable(s)." >&2
     echo "This script should be started by hald." >&2
     exit 1
@@ -46,7 +47,7 @@ fi
 # TODO: need to select storage-[fixed|removable][-change-uid]
 #POLICY=hal-storage-fixed-mount
 #if [ "$HAL_METHOD_INVOKED_BY_UID" != "0" ] ; then
-#    polkit-is-privileged --privilege $POLICY --user $HAL_METHOD_INVOKED_BY_UID
+#    RESULT=$(polkit-is-privileged --privilege $POLICY --user $HAL_METHOD_INVOKED_BY_UID 2>&1)
 #    IS_PRIVILEGED=$?
 #    if [ "$IS_PRIVILEGED" != "0" ] ; then
 #	echo org.freedesktop.Hal.Device.PermissionDeniedByPolicy >&2
@@ -55,9 +56,12 @@ fi
 #    fi
 #fi
 
-if [ -n "$HALD_UNAME_S" -a -x ./$0-$HALD_UNAME_S ]; then
-    exec ./$0-$HALD_UNAME_S $@
+export MOUNT_POINT
+
+if [ -n "$HALD_UNAME_S" -a -x $0-$HALD_UNAME_S ]; then
+    exec $0-$HALD_UNAME_S $@
 else
+    echo "org.freedesktop.Hal.Device.UnknownError" >&2
     echo "No back-end for your operating system" >&2
     exit 1
 fi
diff --git a/tools/linux/hal-system-storage-eject-linux b/tools/linux/hal-system-storage-eject-linux
--- a/tools/linux/hal-system-storage-eject-linux
+++ b/tools/linux/hal-system-storage-eject-linux
@@ -12,10 +12,10 @@
 # Only allow ^a-zA-Z0-9_= in the string because otherwise someone may
 # pass e.g. umask=0600,suid,dev or umask=`/bin/evil`
 
-rc=0
 read GIVEN_EJECTOPTIONS
 GIVEN_EJECTOPTIONS="`echo \"$GIVEN_EJECTOPTIONS\" | tr -cd \"a-zA-Z0-9_=[:space:]\"`"
-RESULT=$(eject "$HAL_PROP_BLOCK_DEVICE" 2>&1)
+
+RESULT=$(eject $GIVEN_EJECTOPTIONS "$HAL_PROP_BLOCK_DEVICE" 2>&1)
 
 if [ $? -ne 0 ]; then
     case "$RESULT" in
@@ -25,7 +25,7 @@ if [ $? -ne 0 ]; then
 	    ;;
 	*)
 	    echo "org.freedesktop.Hal.Device.Volume.UnknownFailure" >&2
-	    echo "Unknown failure." >&2
+	    echo "Unknown failure: $RESULT" >&2
     esac
     exit 1
 fi
diff --git a/tools/linux/hal-system-storage-unmount-linux b/tools/linux/hal-system-storage-unmount-linux
--- a/tools/linux/hal-system-storage-unmount-linux
+++ b/tools/linux/hal-system-storage-unmount-linux
@@ -14,6 +14,12 @@
 read GIVEN_UNMOUNTOPTIONS
 GIVEN_UNMOUNTOPTIONS="`echo \"$GIVEN_UNMOUNTOPTIONS\" | tr -cd \"a-zA-Z0-9_=[:space:]\"`"
 
+if [ -z "$MOUNT_POINT" ]; then
+	echo "org.freedesktop.Hal.Device.Volume.UnknownMountpoint" >&2
+	echo "Missing mountpoint, cannot figure out where device is mounted." >&2
+	exit 1
+fi
+
 if [ -n "$GIVEN_UNMOUNTOPTIONS" ]; then
     for OPTION in $GIVEN_UNMOUNTOPTIONS; do
 	OPTION_WAS_OK="0"
@@ -60,7 +66,7 @@ if [ $? -ne 0 ]; then
 	    ;;
 	*)
 	    echo "org.freedesktop.Hal.Device.Volume.UnknownFailure" >&2
-	    echo "Unknown failure." >&2
+	    echo "Unknown failure: $RESULT" >&2
     esac
     exit 1
 fi
