Make GetBrightness and SetBrightness take raw, not percentage, values.

diff --git a/tools/hal-system-lcd-set-brightness b/tools/hal-system-lcd-set-brightness
--- a/tools/hal-system-lcd-set-brightness
+++ b/tools/hal-system-lcd-set-brightness
@@ -7,7 +7,7 @@
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
 
-read percentage
+read value
 
 # Check for file existance and that it's writable
 if [ ! -w $HAL_PROP_LINUX_ACPI_PATH ]; then
@@ -16,8 +16,12 @@ if [ ! -w $HAL_PROP_LINUX_ACPI_PATH ]; then
 	exit 1
 fi
 
-# Work out the abs value
-let "value = ( $percentage * $HAL_PROP_LAPTOP_PANEL_NUM_LEVELS ) / 100"
+# Check for values outside range
+if [ ${value} -lt 0 ] || [ ${value} -gt $HAL_PROP_LAPTOP_PANEL_NUM_LEVELS ]; then
+	echo "org.freedesktop.Hal.Device.LaptopPanel.Invalid" >&2
+	echo "Brightness has to be between 0 and $HAL_PROP_LAPTOP_PANEL_NUM_LEVELS!" >&2
+	exit 1
+fi
 
 if [ "$HAL_PROP_LAPTOP_PANEL_ACPI_METHOD" == "toshiba" ]; then
 	# echo "brightness: {0..x}" >/proc/acpi/toshiba/lcd
