Added checks for needed environment variables to prevent call them from     commandline if a variable is missing. Fixed error messages.

diff --git a/tools/hal-luks-remove.in b/tools/hal-luks-remove.in
--- a/tools/hal-luks-remove.in
+++ b/tools/hal-luks-remove.in
@@ -21,6 +21,13 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 
+# Check for environment variables
+if [ "$HAL_PROP_BLOCK_DEVICE" == "" ] || [ "$HAL_PROP_INFO_UDI" == "" ] || [ "$HAL_PROP_VOLUME_UUID" == "" ] ; then
+        echo "Missing or empty environment variable(s)." >&2
+        echo "This script should be started by hald." >&2
+        exit 1
+fi
+
 CRYPTSETUP=/sbin/cryptsetup
 
 HAL_FIND_BY_PROPERTY=@BINDIR@/hal-find-by-property
diff --git a/tools/hal-system-lcd-get-brightness b/tools/hal-system-lcd-get-brightness
--- a/tools/hal-system-lcd-get-brightness
+++ b/tools/hal-system-lcd-get-brightness
@@ -7,6 +7,13 @@
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
 
+# Check for environment variables
+if [ "$HAL_PROP_LAPTOP_PANEL_ACPI_METHOD" == "" ] || [ "$HAL_PROP_LINUX_ACPI_PATH" == "" ]; then
+	echo "Missing or empty environment variable(s)." >&2
+	echo "This script should be started by hald." >&2
+	exit 1
+fi
+
 # Check for file existance and that it's readable
 if [ ! -r $HAL_PROP_LINUX_ACPI_PATH ]; then
 	echo "org.freedesktop.Hal.Device.LaptopPanel.NotSupported" >&2
@@ -40,7 +47,7 @@ elif [ "$HAL_PROP_LAPTOP_PANEL_ACPI_METHOD" == "sony" ]; then
 	let "value = ${value} - 1"
 else
 	echo "org.freedesktop.Hal.Device.LaptopPanel.NotSupported" >&2
-	echo "No acpi method script found" >&2
+	echo "No ACPI method found" >&2
 	exit 1
 	fi
 
diff --git a/tools/hal-system-lcd-set-brightness b/tools/hal-system-lcd-set-brightness
--- a/tools/hal-system-lcd-set-brightness
+++ b/tools/hal-system-lcd-set-brightness
@@ -7,6 +7,16 @@
 # the Free Software Foundation; either version 2 of the License, or
 # (at your option) any later version.
 
+# Check for environment variables
+if [ "$HAL_PROP_LAPTOP_PANEL_ACPI_METHOD" == "" ] || 
+   [ "$HAL_PROP_LINUX_ACPI_PATH" == "" ] ||
+   [ "$HAL_PROP_LAPTOP_PANEL_NUM_LEVELS" == "" ] ; then
+        echo "Missing or empty environment variable(s)." >&2
+        echo "This script should be started by hald." >&2
+        exit 1
+fi
+
+# read value for set brightness
 read value
 
 # Check for file existance and that it's writable
@@ -44,7 +54,7 @@ elif [ "$HAL_PROP_LAPTOP_PANEL_ACPI_METHOD" == "sony" ]; then
 	echo "$value" > $HAL_PROP_LINUX_ACPI_PATH
 else
 	echo "org.freedesktop.Hal.Device.LaptopPanel.NotSupported" >&2
-	echo "No acpi method script found" >&2
+	echo "No ACPI method found" >&2
 	exit 1
 	fi
 
