port HAL over to use PolicyKit master
In the process, include hal-functions and make out shell-script based
method handlers share that.

diff --git a/privileges/Makefile.am b/privileges/Makefile.am
--- a/privileges/Makefile.am
+++ b/privileges/Makefile.am
@@ -1,17 +1,26 @@
 
 if HAVE_POLKIT
-polkit_privilegedir = $(sysconfdir)/PolicyKit/privilege.d
+polkit_privilegedir = $(sysconfdir)/PolicyKit/privileges
 
-dist_polkit_privilege_DATA =                              \
-	hal-storage-fixed-mount.privilege                 \
-	hal-storage-fixed-mount-all-options.privilege     \
-	hal-storage-removable-mount.privilege             \
-	hal-storage-removable-mount-all-options.privilege \
-	hal-power-suspend.privilege                       \
-	hal-power-hibernate.privilege                     \
-	hal-power-poweroff.privilege                      \
-	hal-power-reboot.privilege                        \
-	hal-power-cpufreq.privilege
+dist_polkit_privilege_DATA =    \
+	hal-storage.priv	\
+	hal-power.priv		\
+	hal-killswitch.priv
+
+if HAVE_ACLMGMT
+dist_polkit_privilege_DATA += hal-device-file.priv
+endif
+
+check:
+	for f in $(dist_polkit_privilege_DATA); do \
+          echo "Validating privilege file: $$f"; \
+          $(POLKIT_PRIVILEGE_FILE_VALIDATE) --file $(srcdir)/$$f; \
+          if [ "$$?" != "0" ]; then \
+            echo "failed"; \
+            exit 1; \
+          fi; \
+        done
+
 endif
 
 clean-local :
